name: Feature Request
description: Create a feature request
title: "[Feature Request]: "
labels: ["feature request"]
assignees:
  - Not-Jayy
body:
  - type: textarea
    id: contact
    attributes:
      label: Explanation
      description: Explain this new feature you want.
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      description: How will it benefit the bot overall?
    validations:
      required: true